[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tiled_export"
version = "1.0.0"
dependencies = [
    "zstd",
]

[project.scripts]
tiled-export = "tiled_export.main:main"
