name: Test

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install pytest
        shell: bash
        run: pip install pytest

      - name: Install project requirements
        shell: bash
        run: pip install -r requirements.txt

      - name: Run tests
        shell: bash
        run: python -m pytest
